const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  background: '#fff',
  errorBackground: 'red',
  warningBackground: '#eaeb5e',
  noticeBackground: tintColor,
  text: 'rgba(96,100,109, 1)',
  disabledText: 'rgba(96,100,109, 0.5)',
  warningText: '#666804',
  errorText: '#fff',
  noticeText: '#fff',
  chartAxis: 'rgba(96,100,109, 1)',
  chartGrid: 'rgba(96,100,109, 0.1)',
  chartLine: tintColor,
  chartFill: tintColor,
  button: tintColor,
  buttonLight: 'rgba(47,149,220, 0.25)',
  buttonOff: '#ccc',
  buttonOffLight: '#eee',
};
